/**
 * Mock data for Friend Circles
 */

export const mockCircles = [
  {
    id: 'circle-1',
    name: 'College Friends',
    adminId: 'current-user',
    members: [
      { 
        id: 'user-1', 
        name: 'Alex Johnson', 
        email: 'alex@university.edu',
        trustBadge: 'Good', 
        personalTrustScore: 92,
        repaymentRate: 95,
        repaymentStreak: 12,
        totalLoans: 8,
        defaultedLoans: 0,
        isAdmin: false,
      },
      { 
        id: 'user-2', 
        name: 'Sarah Chen', 
        email: 'sarah@university.edu',
        trustBadge: 'Good', 
        personalTrustScore: 96,
        repaymentRate: 98,
        repaymentStreak: 15,
        totalLoans: 10,
        defaultedLoans: 0,
        isAdmin: false,
      },
      { 
        id: 'user-3', 
        name: 'Mike Davis', 
        email: 'mike@university.edu',
        trustBadge: 'Average', 
        personalTrustScore: 78,
        repaymentRate: 85,
        repaymentStreak: 5,
        totalLoans: 6,
        defaultedLoans: 1,
        isAdmin: false,
      },
    ],
    circleTrustScore: 92,
    totalLoans: 24,
    activeLoans: 3,
    completedLoans: 21,
    defaultedLoans: 1,
    createdAt: '2024-01-15',
  },
  {
    id: 'circle-2',
    name: 'Study Group',
    adminId: 'user-4',
    members: [
      { 
        id: 'user-4', 
        name: 'Emma Wilson', 
        email: 'emma@university.edu',
        trustBadge: 'Good', 
        personalTrustScore: 94,
        repaymentRate: 97,
        repaymentStreak: 18,
        totalLoans: 12,
        defaultedLoans: 0,
        isAdmin: true,
      },
      { 
        id: 'user-5', 
        name: 'David Lee', 
        email: 'david@university.edu',
        trustBadge: 'Average', 
        personalTrustScore: 82,
        repaymentRate: 88,
        repaymentStreak: 8,
        totalLoans: 7,
        defaultedLoans: 0,
        isAdmin: false,
      },
    ],
    circleTrustScore: 88,
    totalLoans: 19,
    activeLoans: 2,
    completedLoans: 17,
    defaultedLoans: 0,
    createdAt: '2024-02-01',
  },
];

export const mockLoans = [
  {
    id: 'loan-1',
    circleId: 'circle-1',
    lenderId: 'current-user',
    borrowerId: 'user-1',
    borrowerName: 'Alex Johnson',
    amount: 500,
    purpose: 'Food',
    status: 'Active',
    createdAt: '2024-03-01',
    dueDate: '2024-04-01',
    gracePeriod: 7,
    remindersSent: 0,
    isOverdue: false,
  },
  {
    id: 'loan-2',
    circleId: 'circle-1',
    lenderId: 'current-user',
    borrowerId: 'user-2',
    borrowerName: 'Sarah Chen',
    amount: 300,
    purpose: 'Books',
    status: 'Active',
    createdAt: '2024-03-10',
    dueDate: '2024-04-10',
    gracePeriod: 7,
    remindersSent: 0,
    isOverdue: false,
  },
];

